name: pypi publish

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: bundle
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          python setup.py sdist bdist_wheel
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          # Password for your PyPI user or an access token
          password: ${{ secrets.pypi_token }}
